
line.bot:
  channel-token: 1SvItfz3nTuNn5thFJawFmZsiwGyRAuj1vJlgXrKd+rEjPiQw52zIRl7tcrcnPpN2l3rBd3EVCoLhPpOPY/mhF2LjGCNsdxGRcblFn9Tr+5LsqQR3U5KQ25Z0jiAjVVp6AFmZTlqXBK/Bw51LYAw6gdB04t89/1O/w1cDnyilFU=
  channel-secret: d3b8521a93b4a82df3cb2b9502995463
  handler.path: /callback
